server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: file:C:/Users/roman.zeylikovich/IdeaProjects/Cloud-Native-Applications-in-Java/Chapter07
