server:
  port: 8085

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    register-with-eureka: true
    fetch-registry: true
management:
  security:
    enabled: false
logging:
  level: debug
spring:
  data:
    mongodb:
      database: masterdb
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: true

jms:
  ProductTopic: ProductT