server:
  port: 8082

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    register-with-eureka: true
    fetch-registry: true
management:
  security:
    enabled: false
logging:
  level: debug
spring:
  data:
    mongodb:
      database: masterdb
