server:
  port: 8086

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    register-with-eureka: true
    fetch-registry: true
logging:
  level: debug
spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: true

jms:
  ProductTopic: ProductT